services:
  app:
    build: .
    ports:
      - "${EXTERNAL_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production

    volumes:
      - football_db_data:/app/cache

volumes:
  football_db_data:
    driver: local
